### ISSUE TITLE
Denodo scanner is not able to pull all the parent names from the EDC 

### ISSUE THREAD

**Issue by zfWazid** [Informatica-EIC/Custom-Scanners#51] opened 2022-11-16 08:20 UTC
We have created custom scanner as per the suggestion provided below

https://www.informatica.com/content/dam/informatica-marketplace/documents/DENODO_custom_scanner.pdf

![Parentnamemissing](https://user-images.githubusercontent.com/109784053/202122091-dcc0a78f-deb7-4339-b267-ac747d0ab5f6.PNG)

And also We tried connection Denodo via JDBC also but this is failing when we are enabling "profiling" Data discovery options

"Please let us know if can acheive profiling via Denodo JDBC drivers" ?

**Comment by darren-wrigley** [comment] 2022-11-16 19:45
there is a bug/error in Axon where it was not properly handling the core.dataSetUuid property for table/view columns.  recent versions of the denodo scanner (1.1.000+) do not use this property (value is empty) to workaround that issue.  
this may filter up to marketplace with the parent link.

I have been trying to get the download updated on marketplace - however that process is taking much longer than expected
you can try the version here:-  [https://github.com/Informatica-EIC/Custom-Scanners/blob/master/Denodo_Scanner/packaged/DenodoScanner.zip]

for the 2nd question - the denodo custom scanner does not currently work with profiling - for that to happen, a .csv file for each denodo table/view would need to be created in a tsftp folder & then the custom scanner framework can be configured to run some (not all) profiling.

if you are using a JDBC scan for denodo - profiling should work, but you will not have any lineage for the denodo objects, either within denodo, or to the upstream datasource objects.

**Comment by zfWazid** [comment] 2022-11-24 06:06
Denodo test connection is working from LDM ADMIN but same test connection is not working from Informatica Admin console(connections tab where we have created0

Please let us know what driver name we should keep the test connection work?
We are trying this to run the Data discovery option for Denodo_JDBC

![DenodoDriverslocation](https://user-images.githubusercontent.com/109784053/203706572-53614326-81d3-4523-b2e2-77b9c85fd1b8.PNG)
![Denodo1](https://user-images.githubusercontent.com/109784053/203706576-0851d54c-f314-46da-a537-0b368758ddbe.PNG)
![Denodo](https://user-images.githubusercontent.com/109784053/203706580-5b63246a-fb15-4feb-afa2-6a0880147166.PNG)

**Comment by zfWazid** [comment] 2022-11-28 04:56
Hi Darren,

Please help us on this

Thanks
Wazid

**Comment by darren-wrigley** [comment] 2022-11-28 16:32
i can only reproduce that issue if i set the JDBC Driver class name to com.denodo.vdb.jdbcdriver.VDBJDBCDriver in the connection from admin console.  it gives me this message:_

> The requested operation could not be performed due to the following error : The JDBC driver class name com.denodo.vdb.jdbcdriver.VDBJDBCDriver in the connection does not match with the JDBC driver class name com.denodo.vdp.jdbc.Driver used in the connection string jdbc:vdb://dw-sndbox01-w.infaaws.com:9999/tutorial?chunkTimeout=2000. Specify the correct connection string and the JDBC driver class name for the connection object.

since that test connect appears to be using com.denodo.vdb.jdbcdriver.VDBJDBCDriver - you can always try it.  
there isn't  much more i can do - since i can't reproduce it & it is not related to the denodo scanner.

some things you can look at:-
- in your $INFA_HOME/externaljdbcjars folder - you have copied all of  the denodo scanner lib files - this is not necessary.  best to remove all and copy only the denodo jdbc driver jar file from your installation (not the one delivered with the scanner) since that will be the correct version for your denodo instance(s).

**Comment by zfWazid** [comment] 2022-12-06 08:29
ok Thank now i'm able to test JDBC connection successfully. 

But the profiling is still failing with 

Function [INFASQLConnectW] failed in adapter [/infaedc/infa/plugins/dynamic/infajdbcruntime/libinfajdbc.so

![Profile1](https://user-images.githubusercontent.com/109784053/205855777-2f060568-73a7-4c9c-b724-5ed950dd8e56.PNG)
![Profile](https://user-images.githubusercontent.com/109784053/205855786-3f057a14-eee6-4b6d-9852-2381c5ae6ce2.PNG)

[7c6934bf-6baf-47f8-88f7-d772f32b09db.zip](https://github.com/Informatica-EIC/Custom-Scanners/files/10164018/7c6934bf-6baf-47f8-88f7-d772f32b09db.zip)

**Comment by darren-wrigley** [comment] 2022-12-06 20:10
have you raised a support case with the platform team?  i tried to reproduce, for jdbc connection i had to set ExecutionContextOptions.JVMMaxMemory custom property in the DIS (from this KB article:  [https://knowledge.informatica.com/s/article/578923?language=en_US](https://knowledge.informatica.com/s/article/578923?language=en_US) ) 

i also set the sql identifier character to double-quotes and support mixed case identifiers to true.

is it working for other tables/views, or only failing for char[0] columns?

**Comment by darren-wrigley** [comment] 2024-06-20 19:50
closing, no-activity/comments - a new ticket could be created for this if needed.  does not appear to be an issue with the scanner

**Closed by darren-wrigley** 2024-06-20 19:50 UTC
